language: node_js
node_js:
- node
before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
  -in deploy_key.enc -out ./deploy_key -d
- npm i -g npm@latest
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- ssh-add ./deploy_key
- git remote add deploy https://github.com/OliRadlett/f28wp
- git push deploy
after_script:
- ssh -i ./deploy_key root@oliradlett.co.uk cd /var/www/html/f28wp && git pull origin
  master
